hl.on("hyprland.start", function ()
  hl.exec_cmd("waybar")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("dunst")
  -- hl.exec_cmd("swaync")
  -- hl.exec_cmd("~/.local/share/koda/bin/koda-init-wallpaper")
end)
