# Submaps

bind=$mainMod, E ,submap, name
bind=$mainMod, E ,exec, pkill -RTMIN+9 waybar
submap=name

bind= , escape , submap, reset
bind= , escape , exec, pkill -RTMIN+9 waybar
submap=reset

# --- System --- #
bind=$mainMod, Escape, submap, 󰐥
bind=$mainMod, Escape, exec, pkill -RTMIN+9 waybar
submap=󰐥

# Lock
bind = , L, exec, hyprlock
bind = , L, submap, reset
bind = , L, exec, pkill -RTMIN+9 waybar

# Sleep
bind = , S, exec, systemctl suspend
bind = , S, submap, reset
bind = , S, exec, pkill -RTMIN+9 waybar

# Reboot
bind = , R, exec, reboot
bind = , R, submap, reset
bind = , R, exec, pkill -RTMIN+9 waybar

# Power Off
bind = , P, exec, shutdown now
bind = , P, submap, reset
bind = , P, exec, pkill -RTMIN+9 waybar

bind= , escape , submap, reset
bind= , escape , exec, pkill -RTMIN+9 waybar
submap=reset
