# Varables
$music = spotify

# --- System --- #
bind=$mainMod, Escape, submap, 󰐥
bind=$mainMod, Escape, exec, pkill -RTMIN+9 waybar
submap=󰐥

# Lock
bind = , L, exec, hyprlock
bind = , L, submap, reset
bind = , L, exec, pkill -RTMIN+9 waybar

# Sleep
bind = , S, exec, systemctl suspend
bind = , S, submap, reset
bind = , S, exec, pkill -RTMIN+9 waybar

# Reboot
bind = , R, exec, reboot
bind = , R, submap, reset
bind = , R, exec, pkill -RTMIN+9 waybar

# Power Off
bind = , P, exec, shutdown now
bind = , P, submap, reset
bind = , P, exec, pkill -RTMIN+9 waybar

# Koda Config
bind = , K, exec, /home/nnovadev/.local/share/koda/bin/koda-floating-window kitty --class=nvim -e nvim ~/.local/share/koda/
bind = , K, submap, reset
bind = , K, exec, pkill -RTMIN+9 waybar

# Hyprland Config
bind = , H, exec, /home/nnovadev/.local/share/koda/bin/koda-floating-window kitty --class=nvim -e nvim ~/.config/hypr
bind = , H, submap, reset
bind = , H, exec, pkill -RTMIN+9 waybar

# Nvim Config
bind = , N, exec, /home/nnovadev/.local/share/koda/bin/koda-floating-window kitty --class=nvim -e nvim ~/.config/nvim
bind = , N, submap, reset
bind = , N, exec, pkill -RTMIN+9 waybar

# .zshrc Config
bind = , Z, exec, /home/nnovadev/.local/share/koda/bin/koda-floating-window kitty --class=nvim -e nvim ~/.zshrc
bind = , Z, submap, reset
bind = , Z, exec, pkill -RTMIN+9 waybar

# Update System
bind = , U, exec, /home/nnovadev/.local/share/koda/bin/koda-floating-window kitty --class=pacman -e sudo pacman -Syu
bind = , U, submap, reset
bind = , U, exec, pkill -RTMIN+9 waybar

bind= , escape , submap, reset
bind= , escape , exec, pkill -RTMIN+9 waybar
submap=reset

# --- Media --- #
bind = $mainMod, M, submap, 󰋋
submap = 󰋋

bind = , I, exec, playerctl previous
bind = , O, exec, playerctl --player=spotify play-pause
bind = , P, exec, playerctl next

# start music player
bind = , M, exec, $music
bind = , M, submap, reset

bind = , escape, submap, reset
submap = reset
