preload = /home/nnovadev/.local/share/koda/themes/adok/wallpapers/5-arch-minimalist.jpg

# Appliquer le wallpaper à tous les moniteurs
wallpaper = eDP-1,/home/nnovadev/.local/share/koda/themes/adok/wallpapers/5-arch-minimalist.jpg
wallpaper = HDMI-A-1,/home/nnovadev/.local/share/koda/themes/adok/wallpapers/5-arch-minimalist.jpg

# Fallback pour tout autre moniteur
wallpaper = ,/home/nnovadev/.local/share/koda/themes/adok/wallpapers/5-arch-minimalist.jpg

splash = false
ipc = on
