input {
    kb_layout = us, us(intl)
    kb_options = caps:escape, grp:alt_space_toggle
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
