# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Set border color to red when Full width
windowrule = border_color rgb(770000), match:fullscreen 1

